# Generated by Django 5.1.4 on 2024-12-19 15:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="phone",
            field=models.CharField(
                blank=True,
                help_text="Введите номер телефона",
                max_length=30,
                null=True,
                verbose_name="Телефон",
            ),
        ),
    ]
