# Generated by Django 5.1.4 on 2025-01-15 11:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Ad",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Введите название товара",
                        max_length=255,
                        verbose_name="Название товара",
                    ),
                ),
                (
                    "price",
                    models.PositiveIntegerField(
                        help_text="Введите цену товара", verbose_name="Цена товара"
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        help_text="Добавьте описание товара",
                        verbose_name="Описание товара",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Автоматически устанавливается при создании",
                        verbose_name="Дата и время создания",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Автоматически обновляется при редактировании",
                        verbose_name="Дата и время обновления",
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        help_text="Пользователь, который создал объявление",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ads",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Автор объявления",
                    ),
                ),
            ],
            options={
                "verbose_name": "Объявление",
                "verbose_name_plural": "Объявления",
                "ordering": ["-created_at"],
            },
        ),
    ]
